# Generated by Django 4.1.3 on 2022-11-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('userphone', models.CharField(max_length=32)),
                ('user_qq', models.CharField(max_length=32, verbose_name='qq号码')),
            ],
        ),
    ]
