# Generated by Django 4.1.3 on 2022-12-04 22:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('first_add', models.DateTimeField(auto_now_add=True)),
                ('price', models.CharField(max_length=32)),
                ('num', models.CharField(max_length=32)),
                ('sales', models.CharField(default='0', max_length=32)),
                ('category', models.CharField(max_length=32)),
                ('myimage', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('userphone', models.CharField(max_length=32)),
                ('user_qq', models.CharField(max_length=32)),
            ],
        ),
    ]
