# Generated by Django 4.1.3 on 2022-12-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('shop_num', models.CharField(max_length=16)),
                ('shop_id', models.CharField(max_length=64)),
            ],
        ),
    ]
