# Generated by Django 4.1.3 on 2022-11-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_qq',
            field=models.CharField(max_length=32),
        ),
    ]
