# Generated by Django 4.1.3 on 2022-11-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_user_user_qq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=32)),
                ('num', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=32)),
                ('main_img', models.CharField(max_length=200)),
                ('detal_img', models.CharField(max_length=2000)),
            ],
        ),
    ]
