# Generated by Django 4.1.3 on 2022-12-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_announcement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_cart',
            name='shop_num',
            field=models.IntegerField(max_length=16),
        ),
    ]
