# Generated by Django 4.1.3 on 2022-12-15 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_shop_cart_shop_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_cart',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
    ]
