# Generated by Django 4.1.3 on 2022-12-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_order_alter_shop_cart_shop_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shop_list',
            field=models.CharField(max_length=512),
        ),
    ]
