# Generated by Django 4.1.3 on 2022-12-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_order_shop_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_image',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
