# Generated by Django 4.1.3 on 2022-12-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_order_first_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='express_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='harvest_type',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
